[book]
authors = ["wangzheng422"]
language = "zh"
multilingual = false
src = "redhat"
title = "OpenShift4 慢慢走"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/wangzheng422/docker_env"
edit-url-template = "https://github.com/wangzheng422/docker_env/blob/dev/{path}"
# additional-css = ["theme1/custom.css"]

[output.html.print]
enable = true